default:
  base_path: "https://trace.virtual.uniandes.edu.co/colopendata/"
  DANE_CNPV_2018_Hogares: "DANE_CNPV_2018_Hogares.xlsx"
  DANE_CNPV_2018_Personas_Demografico: "DANE_CNPV_2018_Personas_Demografico.xlsx"
  DANE_CNPV_2018_Personas_Social: "DANE_CNPV_2018_Personas_Social.xlsx"
  DANE_CNPV_2018_Viviendas: "DANE_CNPV_2018_Viviendas.xlsx"
  DANE_MGNCNPV_2018_DPTO: "DANE_MGNCNPV_2018_DPTO.zip"
  DANE_MGNCNPV_2018_MPIO: "DANE_MGNCNPV_2018_MPIO.zip"
  DANE_MGNCNPV_2018_MPIOCL: "DANE_MGNCNPV_2018_MPIOCL.zip"
  DANE_MGNCNPV_2018_MZN: "DANE_MGNCNPV_2018_MZN.zip"
  DANE_MGNCNPV_2018_SECR: "DANE_MGNCNPV_2018_SECR.zip"
  DANE_MGNCNPV_2018_SECU: "DANE_MGNCNPV_2018_SECU.zip"
  DANE_MGNCNPV_2018_SETR: "DANE_MGNCNPV_2018_SETR.zip"
  DANE_MGNCNPV_2018_SETU: "DANE_MGNCNPV_2018_SETU.zip"
  DICT_DANE_MGNCNPV_2018_DPTO: "dictionaries/DANE_MGNCNPV_2018_DPTO.csv"
  DICT_DANE_MGNCNPV_2018_MPIO: "dictionaries/DANE_MGNCNPV_2018_MPIO.csv"
  DICT_DANE_MGNCNPV_2018_MPIOCL: "dictionaries/DANE_MGNCNPV_2018_MPIOCL.csv"
  DICT_DANE_MGNCNPV_2018_MZN: "dictionaries/DANE_MGNCNPV_2018_MZN.csv"
  DICT_DANE_MGNCNPV_2018_SECR: "dictionaries/DANE_MGNCNPV_2018_SECR.csv"
  DICT_DANE_MGNCNPV_2018_SECU: "dictionaries/DANE_MGNCNPV_2018_SECU.csv"
  DICT_DANE_MGNCNPV_2018_SETR: "dictionaries/DANE_MGNCNPV_2018_SETR.csv"
  DICT_DANE_MGNCNPV_2018_SETU: "dictionaries/DANE_MGNCNPV_2018_SETU.csv"
  DICT_IDEAM_CLIMATE_2023: "dictionaries/IDEAM_CLIMATE_2023.csv"
  