default:
  base_path: "https://trace.virtual.uniandes.edu.co/colopendata"
  documentation: "doc_and_dict/documentation.csv"
  dictionaries: "doc_and_dict"
  demographic: "demographic"
  households: "cnpv/hogares"
  dwellings: "cnpv/viviendas"
  persons_social: "cnpv/personas_social"
  persons_demographic: "cnpv/personas_demografico"
  geospatial: "geospatial"
  maps: "mgn/mgncnpv"
  climate: "climate"
  IDEAM_STATIONS_2023_MAY: "doc_and_dict/IDEAM_STATIONS_2023_MAY.csv"
