default:
  base_path: "https://trace.virtual.uniandes.edu.co/colopendata/"
  DANE_CNPV_2018_Hogares: "DANE_CNPV_2018_Hogares.XLSX"
  DANE_CNPV_2018_Personas_Demografico: "DANE_CNPV_2018_Personas_Demografico.xlsx"
  DANE_CNPV_2018_Personas_Social: "DANE_CNPV_2018_Personas_Social.xlsx"
  DANE_CNPV_2018_Viviendas: "DANE_CNPV_2018_Viviendas.xlsx"
  DANE_MGNCNPV_2018_DPTO: "DANE_MGNCNPV_2018_DPTO.zip"
  DANE_MGNCNPV_2018_MPIO: "DANE_MGNCNPV_2018_MPIO.zip"
  DANE_MGNCNPV_2018_MPIOCL: "DANE_MGNCNPV_2018_MPIOCL.zip"
  DANE_MGNCNPV_2018_MZN: "DANE_MGNCNPV_2018_MZN.zip"
  DANE_MGNCNPV_2018_SECR: "DANE_MGNCNPV_2018_SECR.zip"
  DANE_MGNCNPV_2018_SECU: "DANE_MGNCNPV_2018_SECU.zip"
  DANE_MGNCNPV_2018_SETR: "DANE_MGNCNPV_2018_SETR.zip"
  DANE_MGNCNPV_2018_SETU: "DANE_MGNCNPV_2018_SETU.zip"
  