default:
  base_path: "https://trace.virtual.uniandes.edu.co/colopendata/"
  documentation: "doc_and_dict/documentation.csv"
  DANE_MGNCNPV_2018_DPTO: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_DPTO.zip"
  DANE_MGNCNPV_2018_MPIO: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_MPIO.zip"
  DANE_MGNCNPV_2018_MPIOCL: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_MPIOCL.zip"
  DANE_MGNCNPV_2018_MZN: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_MZN.zip"
  DANE_MGNCNPV_2018_SECR: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_SECR.zip"
  DANE_MGNCNPV_2018_SECU: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_SECU.zip"
  DANE_MGNCNPV_2018_SETR: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_SETR.zip"
  DANE_MGNCNPV_2018_SETU: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_SETU.zip"
  DANE_MGNCNPV_2018_ZU: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_ZU.zip"
  IDEAM_CLIMATE_2023_MAY: "climate/IDEAM_CLIMATE_2023_MAY"
  IDEAM_STATIONS_2023_MAY: "climate/IDEAM_STATIONS_2023_MAY.csv"
  DICT_DANE_MGNCNPV_2018_DPTO: "doc_and_dict/DANE_MGNCNPV_2018_DPTO.csv"
  DICT_DANE_MGNCNPV_2018_MPIO: "doc_and_dict/DANE_MGNCNPV_2018_MPIO.csv"
  DICT_DANE_MGNCNPV_2018_MPIOCL: "doc_and_dict/DANE_MGNCNPV_2018_MPIOCL.csv"
  DICT_DANE_MGNCNPV_2018_MZN: "doc_and_dict/DANE_MGNCNPV_2018_MZN.csv"
  DICT_DANE_MGNCNPV_2018_SECR: "doc_and_dict/DANE_MGNCNPV_2018_SECR.csv"
  DICT_DANE_MGNCNPV_2018_SECU: "doc_and_dict/DANE_MGNCNPV_2018_SECU.csv"
  DICT_DANE_MGNCNPV_2018_SETR: "doc_and_dict/DANE_MGNCNPV_2018_SETR.csv"
  DICT_DANE_MGNCNPV_2018_SETU: "doc_and_dict/DANE_MGNCNPV_2018_SETU.csv"
  DICT_IDEAM_CLIMATE_2023_MAY: "doc_and_dict/IDEAM_CLIMATE_2023.csv"
