default:
  base_path: "https://trace.virtual.uniandes.edu.co/colopendata/"
  documentation: "doc_and_dict/documentation.csv"
  DANE_MGNCNPV_2018_DPTO: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_DPTO.zip"
  DANE_MGNCNPV_2018_MPIO: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_MPIO.zip"
  DANE_MGNCNPV_2018_MPIOCL: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_MPIOCL.zip"
  DANE_MGNCNPV_2018_MZN: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_MZN.zip"
  DANE_MGNCNPV_2018_SECR: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_SECR.zip"
  DANE_MGNCNPV_2018_SECU: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_SECU.zip"
  DANE_MGNCNPV_2018_SETR: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_SETR.zip"
  DANE_MGNCNPV_2018_SETU: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_SETU.zip"
  DANE_MGNCNPV_2018_ZU: "geospatial/mgn/mgncnpv/DANE_MGNCNPV_2018_ZU.zip"
  DANE_CNPVH_2018_1HD: "demographic/cnpv/hogares/DANE_CNPVH_2018_1HD.csv"
  DANE_CNPVH_2018_1HM: "demographic/cnpv/hogares/DANE_CNPVH_2018_1HM.csv"
  DANE_CNPVH_2018_2HD: "demographic/cnpv/hogares/DANE_CNPVH_2018_2HD.csv"
  DANE_CNPVH_2018_2HM: "demographic/cnpv/hogares/DANE_CNPVH_2018_2HM.csv"
  DANE_CNPVH_2018_3HD: "demographic/cnpv/hogares/DANE_CNPVH_2018_3HD.csv"
  DANE_CNPVH_2018_3HM: "demographic/cnpv/hogares/DANE_CNPVH_2018_3HM.csv"
  DANE_CNPVPD_2018_1PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_1PD.csv"
  DANE_CNPVPD_2018_1PM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_1PM.csv"
  DANE_CNPVPD_2018_2PT: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_2PT.csv"
  DANE_CNPVPD_2018_3PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_3PD.csv"
  DANE_CNPVPD_2018_3PM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_3PM.csv"
  DANE_CNPVPD_2018_4PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_4PD.csv"
  DANE_CNPVPD_2018_4PM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_4PM.csv"
  DANE_CNPVPD_2018_5APD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_5APD.csv"
  DANE_CNPVPD_2018_5APM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_5APM.csv"
  DANE_CNPVPD_2018_5BPD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_5BPD.csv"
  DANE_CNPVPD_2018_5BPM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_5BPM.csv"
  DANE_CNPVPD_2018_6PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_6PD.csv"
  DANE_CNPVPD_2018_7PP: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_7PP.csv"
  DANE_CNPVPD_2018_8PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_8PD.csv"
  DANE_CNPVPD_2018_9PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_9PD.csv"
  DANE_CNPVPD_2018_10PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_10PD.csv"
  DANE_CNPVPD_2018_11PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_11PD.csv"
  DANE_CNPVPD_2018_11PP: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_11PP.csv"
  DANE_CNPVPD_2018_12PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_12PD.csv"
  DANE_CNPVPD_2018_12PM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_12PM.csv"
  DANE_CNPVPD_2018_13PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_13PD.csv"
  DANE_CNPVPD_2018_13PM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_13PM.csv"
  DANE_CNPVPD_2018_14APD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_14APD.csv"
  DANE_CNPVPD_2018_14APM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_14APM.csv"
  DANE_CNPVPD_2018_14BPD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_14BPD.csv"
  DANE_CNPVPD_2018_14BPM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_14BPM.csv"
  DANE_CNPVPD_2018_15PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_15PD.csv"
  DANE_CNPVPD_2018_15PM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_15PM.csv"
  DANE_CNPVPD_2018_16PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_16PD.csv"
  DANE_CNPVPD_2018_16PM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_16PM.csv"
  DANE_CNPVPD_2018_17PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_17PD.csv"
  DANE_CNPVPD_2018_17PM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_17PM.csv"
  DANE_CNPVPD_2018_18PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_18PD.csv"
  DANE_CNPVPD_2018_18PM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_18PM.csv"
  DANE_CNPVPD_2018_19PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_19PD.csv"
  DANE_CNPVPD_2018_19PM: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_19PM.csv"
  DANE_CNPVPD_2018_20APD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_20APD.csv"
  DANE_CNPVPD_2018_20PD: "demographic/cnpv/personas_demografico/DANE_CNPVPD_2018_20PD.csv"
  DANE_CNPPS_2018_1APM: "demographic/cnpv/personas_social/DANE_CNPPS_2018_1APM.csv"
  DANE_CNPVPS_2018_1AAPD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_1AAPD.csv"
  DANE_CNPVPS_2018_1AAPM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_1AAPM.csv"
  DANE_CNPVPS_2018_1APM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_1APM.csv"
  DANE_CNPVPS_2018_1BPD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_1BPD.csv"
  DANE_CNPVPS_2018_1BPM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_1BPM.csv"
  DANE_CNPVPS_2018_2APD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_2APD.csv"
  DANE_CNPVPS_2018_2BPM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_2BPM.csv"
  DANE_CNPVPS_2018_2PD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_2PD.csv"
  DANE_CNPVPS_2018_2PM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_2PM.csv"
  DANE_CNPVPS_2018_3PD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_3PD.csv"
  DANE_CNPVPS_2018_3PM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_3PM.csv"
  DANE_CNPVPS_2018_4PD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_4PD.csv"
  DANE_CNPVPS_2018_4PM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_4PM.csv"
  DANE_CNPVPS_2018_5PD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_5PD.csv"
  DANE_CNPVPS_2018_5PM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_5PM.csv"
  DANE_CNPVPS_2018_6PD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_6PD.csv"
  DANE_CNPVPS_2018_7PD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_7PD.csv"
  DANE_CNPVPS_2018_7PM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_7PM.csv"
  DANE_CNPVPS_2018_8APD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_8APD.csv"
  DANE_CNPVPS_2018_8APM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_8APM.csv"
  DANE_CNPVPS_2018_8BPD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_8BPD.csv"
  DANE_CNPVPS_2018_8BPM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_8BPM.csv"
  DANE_CNPVPS_2018_9HD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_9HD.csv"
  DANE_CNPVPS_2018_9HM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_9HM.csv"
  DANE_CNPVPS_2018_10HD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_10HD.csv"
  DANE_CNPVPS_2018_10HM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_10HM.csv"
  DANE_CNPVPS_2018_11HD: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_11HD.csv"
  DANE_CNPVPS_2018_11HM: "demographic/cnpv/personas_social/DANE_CNPVPS_2018_11HM.csv"
  DANE_CNPVV_2018_1D: "demographic/cnpv/viviendas/DANE_CNPVV_2018_1D.csv"
  DANE_CNPVV_2018_1M: "demographic/cnpv/viviendas/DANE_CNPVV_2018_1M.csv"
  DANE_CNPVV_2018_2D: "demographic/cnpv/viviendas/DANE_CNPVV_2018_2D.csv"
  DANE_CNPVV_2018_2M: "demographic/cnpv/viviendas/DANE_CNPVV_2018_2M.csv"
  DANE_CNPVV_2018_3D: "demographic/cnpv/viviendas/DANE_CNPVV_2018_3D.csv"
  DANE_CNPVV_2018_3M: "demographic/cnpv/viviendas/DANE_CNPVV_2018_3M.csv"
  DANE_CNPVV_2018_4D: "demographic/cnpv/viviendas/DANE_CNPVV_2018_4D.csv"
  DANE_CNPVV_2018_4M: "demographic/cnpv/viviendas/DANE_CNPVV_2018_4M.csv"
  DANE_CNPVV_2018_5D: "demographic/cnpv/viviendas/DANE_CNPVV_2018_5D.csv"
  DANE_CNPVV_2018_5M: "demographic/cnpv/viviendas/DANE_CNPVV_2018_5M.csv"
  DANE_CNPVV_2018_6D: "demographic/cnpv/viviendas/DANE_CNPVV_2018_6D.csv"
  DANE_CNPVV_2018_6M: "demographic/cnpv/viviendas/DANE_CNPVV_2018_6M.csv"
  DANE_CNPVV_2018_7D: "demographic/cnpv/viviendas/DANE_CNPVV_2018_7D.csv"
  DANE_CNPVV_2018_7M: "demographic/cnpv/viviendas/DANE_CNPVV_2018_7M.csv"
  DANE_CNPVV_2018_8D: "demographic/cnpv/viviendas/DANE_CNPVV_2018_8D.csv"
  DANE_CNPVV_2018_8M: "demographic/cnpv/viviendas/DANE_CNPVV_2018_8M.csv"
  DANE_CNPVV_2018_9D: "demographic/cnpv/viviendas/DANE_CNPVV_2018_9D.csv"
  DANE_CNPVV_2018_9M: "demographic/cnpv/viviendas/DANE_CNPVV_2018_9M.csv"
  DANE_CNPVV_2018_10D: "demographic/cnpv/viviendas/DANE_CNPVV_2018_10D.csv"
  DANE_CNPVV_2018_10M: "demographic/cnpv/viviendas/DANE_CNPVV_2018_10M.csv"
  IDEAM_CLIMATE_2023_MAY: "climate/IDEAM_CLIMATE_2023_MAY"
  IDEAM_STATIONS_2023_MAY: "climate/IDEAM_STATIONS_2023_MAY.csv"
  DICT_DANE_MGNCNPV_2018_DPTO: "doc_and_dict/DANE_MGNCNPV_2018_DPTO.csv"
  DICT_DANE_MGNCNPV_2018_MPIO: "doc_and_dict/DANE_MGNCNPV_2018_MPIO.csv"
  DICT_DANE_MGNCNPV_2018_MPIOCL: "doc_and_dict/DANE_MGNCNPV_2018_MPIOCL.csv"
  DICT_DANE_MGNCNPV_2018_MZN: "doc_and_dict/DANE_MGNCNPV_2018_MZN.csv"
  DICT_DANE_MGNCNPV_2018_SECR: "doc_and_dict/DANE_MGNCNPV_2018_SECR.csv"
  DICT_DANE_MGNCNPV_2018_SECU: "doc_and_dict/DANE_MGNCNPV_2018_SECU.csv"
  DICT_DANE_MGNCNPV_2018_SETR: "doc_and_dict/DANE_MGNCNPV_2018_SETR.csv"
  DICT_DANE_MGNCNPV_2018_SETU: "doc_and_dict/DANE_MGNCNPV_2018_SETU.csv"
  DICT_IDEAM_CLIMATE_2023_MAY: "doc_and_dict/IDEAM_CLIMATE_2023.csv"
