default:
  base_path: "https://github.com/biomac-lab/data_ColOpenData/blob/main/"
  MGNCNPV_DPTO_2018: "MGN/MGN_CNPV_2018/MGN_NivelDepartamentoIntegrado_CNPV/MGN_AMN_DPTOS.RDS?raw=true"
  MGNCNPV_MPIO_2018: "MGN/MGN_CNPV_2018/MGN_NivelMunicipioIntegrado_CNPV/MGN_AMN_MPIOS.RDS?raw=true"
  CNPVHOG_MPIO_2018: "DEMOGRAFIA/DEMOGRAFIA_Y_POBLACION/CNPV/HOGARES_Cuadros_CNPV_2018.xlsx?raw=true"
  CNPVVIV_MPIO_2018: "DEMOGRAFIA/DEMOGRAFIA_Y_POBLACION/CNPV/VIVIENDAS_Cuadros_CNPV_2018.xlsx?raw=true"
  CHC_TOTAL_2018: "DEMOGRAFIA/DEMOGRAFIA_Y_POBLACION/CHC/anexos-CHC-2021.xlsx?raw=true"
  PP_COL_1950_2019: "PP/NACIONAL/DCD-area-sexo-edad-proypoblacion-Nac-1950-2019.xlsx?raw=true"
  PP_COL_2020_2070: "PP/NACIONAL/DCD-area-sexo-edad-proypoblacion-Nac-2020-2070.xlsx?raw=true"
  PP_DPTO_2005_2019: "PP/DEPARTAMENTAL/DCD-area-sexo-edad-proypoblacion-dep-2005-2019.xlsx?raw=true"
  PP_DPTO_2020_2050: "PP/DEPARTAMENTAL/DCD-area-sexo-edad-proyepoblacion-dep-2020-2050-ActPostCOVID-19.xlsx?raw=true"
  PP_MPIO_2005_2019: "PP/MUNICIPAL/DCD-area-sexo-edad-proypoblacion-Mun-2005-2019.xlsx?raw=true"
  PP_MPIO_2020_2035: "PP/MUNICIPAL/DCD-area-sexo-edad-proypoblacion-Mun-2020-2035-ActPostCOVID-19.xlsx?raw=true"
  